<?php


namespace FunDataProvider;

/**
 * Provider for the Fun Data generator
 */
class FunDataProvider extends \Faker\Provider\Base
{
    public static $names = [
        'Abel Auboisdormant',
        'Agathe Zeblouse',
        'Agnès Téziste',
        'Aïcha Fémal',
        'Alain Di',
        'Alain Parfait',
        'Alain Posteur',
        'Alain Proviste',
        'Alain Térieur',
        'Alain Verse',
        'Alex Térieur',
        'Alex Trémité',
        'Ali Gator',
        'Amédée Pan',
        'Anna Conda',
        'Anna Tomie',
        'Anne Orak',
        'Annie Versaire',
        'Aubin Sahalor',
        'Aude Javel',
        'Aude Vaisselle',
        'Beth Rave',
        'Camille Honête',
        'Candy Raton',
        'Carry Bout',
        'Cathy Mini',
        'Cécile Encieu',
        'Côme Toulemonde',
        'Daisy Dérata',
        'Daisy Draté',
        'Daisy Rable',
        'Eddy Denante',
        'Edith Orial',
        'Eléonore Iléosud',
        'Elie Vadeboncoeur',
        'Ella Danlosse',
        'Elmer Itmieu',
        'Elvire Agoche',
        'Eva Peauré',
        'Eve Rest',
        'Félicie Tation',
        'Gaspard Alizan',
        'Geoffroy Danledo',
        'Gérard Menvussa',
        'Guy Liguili',
        'Guy Tarehéro',
        'Guy Tarembois',
        'Harry Cover',
        'Harry Stocrate',
        'Hassan Cehef',
        'Hilary Amablag',
        'Ines Spéré',
        'Jacques Célère',
        'Jacques Ouzi',
        'Jade Mire',
        'Jean Aimarre',
        'Jean Bambois',
        'Jean Cérien',
        'Jean Tanrien',
        'Jerry Canne',
        'John Atend',
        'John Deuf',
        'Judas Nanas',
        'Jude Orange',
        'Juste Ificatif',
        'Justin Ptipeu',
        'Kelly Diote',
        'Laure Dure',
        'Laurent Gina',
        'Laurent Outan',
        'Lili Coptère',
        'Line Evitable',
        'Luc Ratif',
        'Luc Sation',
        'Lucie Fer',
        'Lydie Commandement',
        'Marc Assin',
        'Marie Rouana',
        'Marie Vière',
        'Maud Erateur',
        'Mehdi Cament',
        'Mehdi Térannée',
        'Milène Micoton',
        'Modeste Oma',
        'Nordine Ateur',
        'Otto Graf',
        'Otto Matik',
        'Oussama Lairbizar',
        'Pacôme Toulemonde',
        'Pat Icier',
        'Paul Emploi',
        'Paul Hémique',
        'Paul Icier',
        'Paul Ution',
        'Paula Roïd',
        'Phil Danstachambre',
        'Phil Defer',
        'Ray Ciproque',
        'Remy Fasol',
        'Renée Sens',
        'Robin Desbois',
        'Sacha Touille',
        'Sam Convient',
        'Samira Bien',
        'Sarah Pelle',
        'Scott Ché',
        'Serge Oin',
        'Sophie Fonfec',
        'Sophie Stiqué',
        'Terry Dicule',
        'Terry Golo',
        'Thérèse Plendissante',
        'Thomas Toketchup',
        'Thomas Wak',
        'Tom Desavoie',
        'Vincent Time',
        'Vishnou Lapaix',
        'Yves Remord',
    ];

    public static function funName()
    {
        return static::randomElement(static::$names);
    }
}
